version: 2
jobs:
  build:
    docker:
      - image: abaez/luarocks:lua5.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: $CIRCLE_WORKING_DIRECTORY/pctl setup
      - run:
          name: Unit Tests
          command: $CIRCLE_WORKING_DIRECTORY/pctl tests
      - run:
          name: Linter
          command: $CIRCLE_WORKING_DIRECTORY/pctl linter
